
package com;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DocumentNotFound", targetNamespace = "http://service.server/")
public class DocumentNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DocumentNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DocumentNotFound_Exception(String message, DocumentNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DocumentNotFound_Exception(String message, DocumentNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.DocumentNotFound
     */
    public DocumentNotFound getFaultInfo() {
        return faultInfo;
    }

}
