
package com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocumentService", targetNamespace = "http://service.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentService {


    /**
     * 
     * @param arg0
     * @throws DocumentNotFound_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.server/", className = "com.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.server/", className = "com.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Document arg0)
        throws DocumentNotFound_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws DocumentAlreadyExist_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.server/", className = "com.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.server/", className = "com.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Document arg0)
        throws DocumentAlreadyExist_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.Document>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.server/", className = "com.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.server/", className = "com.FindAllResponse")
    public List<Document> findAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.Document
     * @throws DocumentNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://service.server/", className = "com.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.server/", className = "com.FindByIdResponse")
    public Document findById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0)
        throws DocumentNotFound_Exception
    ;

}
