
package com.organization.name;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentServiceImplService", targetNamespace = "http://service.server/", wsdlLocation = "file:/C:/Users/Kostay/IdeaProjects/hello-jaxws-master/SoapClient/src/main/resources/wsdl/document.wsdl")
public class DocumentServiceImplService
    extends Service
{

    private final static URL DOCUMENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.organization.name.DocumentServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.organization.name.DocumentServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/Kostay/IdeaProjects/hello-jaxws-master/SoapClient/src/main/resources/wsdl/document.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Kostay/IdeaProjects/hello-jaxws-master/SoapClient/src/main/resources/wsdl/document.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public DocumentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentServiceImplService() {
        super(DOCUMENTSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://service.server/", "DocumentServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns DocumentService
     */
    @WebEndpoint(name = "DocumentServiceImplPort")
    public DocumentService getDocumentServiceImplPort() {
        return super.getPort(new QName("http://service.server/", "DocumentServiceImplPort"), DocumentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentService
     */
    @WebEndpoint(name = "DocumentServiceImplPort")
    public DocumentService getDocumentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server/", "DocumentServiceImplPort"), DocumentService.class, features);
    }

}
